version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  tradutor-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
